# subdir and objects in current dir
SUBDIRS	= 
OBJECTS	= raknet_serv.o raknet_client.o dbop.o mysqlop.o pure_log.o config.o


all:subdirs ${OBJECTS}

	
clean:cleansubdirs
	rm -f ${OBJECTS} *.o
	
include ${MAKEINCLUDE}
